title: Tic Tac Toe
description:
   Game Tic Tac Toe building only with HTML5 using half a million of static web page files.

baseurl: "/pure-html-tic-tac-toe"

exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - generator.py
   - template
   - README.md
   - LICENSE